name: Run long fuzz tests on Btree

on:
  push:
    paths:
      - 'core/storage/btree.rs'
  pull_request:
    paths:
      - 'core/storage/btree.rs'

jobs:
  run-long-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 0 
    
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v1-rust" # can be updated if we need to reset caches due to non-trivial change in the dependencies (for example, custom env var were set for single workspace project)
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Build
      run: cargo build --verbose
    - name: Run ignored long tests
      run: cargo test -- --ignored fuzz_long
      env:
        RUST_BACKTRACE: 1  